# 4. Basic Math, Matrix Operations

In this section, we'll cover some basic operations in TensorFlow. There are many more cool operations not covered here. For a more holistic overview, see [the official API documentation](https://www.tensorflow.org/api_docs/python/tf#functions).

## Scalar Operations

### Arithmetic

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.add(2,3)       # 2 + 3
b = tf.subtract(10,2) # 10 - 2
c = tf.multiply(3,10) # 3 * 10
d = tf.div(30,2)      # 30 / 2
e = tf.pow(2,10)      # 2 ** 10

with tf.Session() as sess: # Evaluate the result
    print('a:',sess.run(a))
    print('b:',sess.run(b))
    print('c:',sess.run(c))
    print('d:',sess.run(d))
    print('e:',sess.run(e))

a: 5
b: 8
c: 30
d: 15
e: 1024


You can also use `tf.constant` to do the following:

In [3]:
a = tf.constant(8)
b = tf.constant(9)
c = a + b
d = a - b
e = 10 * b + a

with tf.Session() as sess:
    print('a:',sess.run(a))
    print('b:',sess.run(b))
    print('c:',sess.run(c))
    print('d:',sess.run(d))
    print('e:',sess.run(e))

a: 8
b: 9
c: 17
d: -1
e: 98


### Data Types

What's wrong with the following?

In [4]:
f = tf.constant(2)
g = tf.constant(3.0)
## This throws an error ##
h = f * g

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Const_3:0", shape=(), dtype=float32)'

The data type should match for operations to be valid. There are data types like `int32`, `float32`, and `float64`. **In general, use `float32`!**

### Exercise
1) Implement the [sigmoid function](https://en.wikipedia.org/wiki/Sigmoid_function). 

2) Evalaute the result for some values.

3) (optional) Plot the sigmoid function using the TensorFlow outputs.

4) Repeat the above for [ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)

In [5]:
# #1
# def sigmoid(x):
#     return 1 / (1 + tf.exp(-x))

# def relu(x):
#     return tf.maximum(0.0,x)

In [6]:
# #2
# with tf.Session() as sess:
#     for x in [0.0, 1.0, 2.0]:
#         print(sess.run(sigmoid(x)))
#         print(sess.run(relu(x)))

In [7]:
# #3
# with tf.Session() as sess:
#     def sigmoid_run(i):
#         return sess.run(sigmoid(i))
#     def relu_run(i):
#         return sess.run(relu(i))

#     nums = np.arange(-6.0,6.0,1)
#     sigmoid_runs = np.vectorize(sigmoid_run)
#     sigmoid_nums = sigmoid_runs(nums)

#     relu_runs = np.vectorize(relu_run)
#     relu_nums = relu_runs(nums)

# import matplotlib.pyplot as plt
# plt.plot(sigmoid_nums)

In [8]:
# plt.plot(relu_nums)

## Matrix Operations

### Products

In [9]:
mat_a = tf.constant([[1,2],[3,4],[5,6]]) # this is how you initialize a matrix
mat_b = tf.constant([[1,2],[2,3]])       # you can also pass in numpy arrays
mat_c = tf.constant([[2,1],[3,2]])

mat_dot1 = tf.matmul(mat_a, mat_b)   # matrix dot product
mat_dot2 = mat_a @ mat_b             # convenint notation for matrix dot product

mat_el1  = tf.multiply(mat_b, mat_c) # element-wise product
mat_el2  = mat_b * mat_c             # convenint notation for element-wise product

In [10]:
print(mat_a) # you can't know the values, but you can know the shapes

Tensor("Const_4:0", shape=(3, 2), dtype=int32)


In [11]:
with tf.Session() as sess:
    print('dot1:\n',sess.run(mat_dot1))
    print('dot2:\n',sess.run(mat_dot2))
    print('el1:\n',sess.run(mat_el1))
    print('el2:\n',sess.run(mat_el2))

dot1:
 [[ 5  8]
 [11 18]
 [17 28]]
dot2:
 [[ 5  8]
 [11 18]
 [17 28]]
el1:
 [[2 2]
 [6 6]]
el2:
 [[2 2]
 [6 6]]


### Broadcasting

In [22]:
mat_e = tf.constant([[2,1],[3,2]])
mat_f = tf.constant([3,4])

mat_broad1 = 2 * mat_e     # each element is multiplied by 2
mat_broad2 = mat_e * mat_f # each row in mat_e is multiplied by mat_f

In [23]:
with tf.Session() as sess:
    print('broad1:\n',sess.run(mat_broad1))
    print('broad2:\n',sess.run(mat_broad2))

broad1:
 [[4 2]
 [6 4]]
broad2:
 [[6 4]
 [9 8]]


#### Exercise
How do you multiply each COLUMN in mat_e by mat_f?

In [19]:
mat_broad4 = mat_e * tf.transpose(mat_f) # each row in mat_e is multiplied by mat_f
with tf.Session() as sess:
    print('broad4:\n',sess.run(mat_broad4))

broad4:
 [[ 6  3]
 [12  8]]


In [20]:
mat_f

<tf.Tensor 'Const_8:0' shape=(1, 2) dtype=int32>

In [21]:
tf.transpose(mat_f)

<tf.Tensor 'transpose_2:0' shape=(2, 1) dtype=int32>

### Reduce

In [14]:
mat_g = tf.constant([[1,2],[1,3]])

red_sum_all = tf.reduce_sum(mat_g)            # reduce matrix to a scalar
red_sum_row = tf.reduce_sum(mat_g, axis = 0)  # reduce the rows
red_sum_col1 = tf.reduce_sum(mat_g, axis = 1) # reduce the columns
red_sum_col2 = tf.reduce_sum(mat_g, axis = 1, keep_dims=True) # keep the dimension

In [15]:
with tf.Session() as sess:
    print('all:\n',sess.run(red_sum_all))
    print('row:\n',sess.run(red_sum_row))
    print('col:\n',sess.run(red_sum_col1))
    print('col:\n',sess.run(red_sum_col2))

all:
 7
row:
 [2 5]
col:
 [3 4]
col:
 [[3]
 [4]]


**Always, always set keep_dims=True!** It keeps column vectors as column vectors. If you don't do that it might cause some really annoying bugs with broadcastng. Also check out `tf.reduce_mean`, `tf.reduce_max`, etc that are also often used.

#### Exercise
1) Say you are given a feature matrix as below (20 samples, 10 features each). Normalize the features (i.e. subtract the mean, divide by the std.dev)

In [25]:
features = tf.constant(np.random.uniform(1,10,[20,10]))

2) Implement the [softmax function](https://en.wikipedia.org/wiki/Softmax_function).

3) Implement ReLU for matrices.

In [26]:
#1
mean, var = tf.nn.moments(features, axes=[0], keep_dims=True)
features_normalized = (features - mean) / var ** (1/2)
with tf.Session() as sess:
    features_normalized_np = sess.run(features_normalized)
print(np.mean(features_normalized_np,axis=0))
print(np.std(features_normalized_np,axis=0))

[  6.77236045e-16  -1.72951931e-16   2.77555756e-16   9.99200722e-17
  -3.33066907e-16  -3.44169138e-16  -3.10862447e-16   1.11022302e-17
  -1.55431223e-16  -2.22044605e-16]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [27]:
def softmax(x):
    exp_x = tf.exp(x)
    sum_exp_x = tf.reduce_sum(exp_x)
    return exp_x / sum_exp_x

In [28]:
x = tf.constant([2, 4, 6, 8],dtype=tf.float32)
with tf.Session() as sess:
    softmax_x_np = sess.run(softmax(x))
softmax_x_np

array([ 0.00214401,  0.0158422 ,  0.11705892,  0.86495489], dtype=float32)

In [96]:
x = tf.constant([-2, 4, -6, 8],dtype=tf.float32)
with tf.Session() as sess:
    relu_x_np = sess.run(relu(x))
softmax_x_np

### Others
Here are other operations I use often:
- `tf.transpose`: matrix transpose
- `tf.equal`: compare matrix element-wise
- `tf.argmax`: get the index of max element
- `tf.gather, tf.slice`: often used for indexing, see the [official guide](https://www.tensorflow.org/api_guides/python/array_ops#Slicing_and_Joining) for details
- `tf.while_loop`: when building a computation graph, don't use python for loop, use this
- `tf.zeros, tf.ones`: same as `np.zeros, np.ones`
- `tf.random_normal, tf.random_uniform`: randomly sample from distributions

## Tips
- Don't use numpy APIs in between when building TensorFlow graphs because it will not be part of your computation graph.
- If there is a numpy way to do it, there is usually a tf way to do it.
- If you think an operation is too complicated, code it up in numpy first, then convert it to tensorflow. Check if the two outputs match.