# Basic Math, Matrix Operations

In this section, we'll cover basic operations in TensorFlow. There are many more cool operations not covered here. For more holistic overview, see [the official API documentation](https://www.tensorflow.org/api_docs/python/tf#functions).

## Scalar Operations

### Arithmetic

In [23]:
import numpy as np
import tensorflow as tf

In [18]:
a = tf.add(2,3)       # 2 + 3
b = tf.subtract(10,2) # 10 - 2
c = tf.multiply(3,10) # 3 * 10
d = tf.div(30,2)      # 30 / 2
e = tf.pow(2,10)      # 2 ** 10

with tf.Session() as sess:
    print('a:',sess.run(a))
    print('b:',sess.run(b))
    print('c:',sess.run(c))
    print('d:',sess.run(d))
    print('e:',sess.run(e))

a: 5
b: 8
c: 30
d: 15
e: 1024


### Data Types

What's wrong with the following?

In [77]:
f = tf.constant(2)
g = tf.constant(3.0)
h = f * g

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Const_58:0", shape=(), dtype=float32)'

In general, use `float32`!

### Excersise
1) Implement the [sigmoid function](https://en.wikipedia.org/wiki/Sigmoid_function). 

2) Evalaute the result for some values.

3) (optional) Plot the sigmoid function using the TensorFlow outputs.

4) Repeat the above for [ReLU](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)

## Matrix Operations

### Products

In [37]:
mat_a = tf.constant([[1,2],[3,4],[5,6]]) # this is how you initialize a matrix
mat_b = tf.constant([[1,2],[2,3]])
mat_c = tf.constant([[2,1],[3,2]])

mat_dot1 = tf.matmul(mat_a, mat_b)   # matrix dot product
mat_dot2 = mat_a @ mat_b             # also matrix dot product

mat_el1  = tf.multiply(mat_b, mat_c) # element-wise product
mat_el2  = mat_b * mat_c             # also element-wise product

In [76]:
print(mat_a) # you can't know the values, but you can know the shapes

Tensor("Const_20:0", shape=(3, 2), dtype=int32)


In [40]:
with tf.Session() as sess:
    print('dot1:\n',sess.run(mat_dot1))
    print('dot2:\n',sess.run(mat_dot2))
    print('el1:\n',sess.run(mat_el1))
    print('el2:\n',sess.run(mat_el2))

dot1:
 [[ 5  8]
 [11 18]
 [17 28]]
dot2:
 [[ 5  8]
 [11 18]
 [17 28]]
el1:
 [[2 2]
 [6 6]]
el2:
 [[2 2]
 [6 6]]


### Broadcasting

In [56]:
mat_e = tf.constant([[2,1],[3,2]])
mat_f = tf.constant([[3,4]])

mat_broad1 = 2 * mat_e # each element is multiplied by 2
mat_broad2 = mat_e * mat_f # each row in mat_e is multiplied by mat_f

In [57]:
with tf.Session() as sess:
    print('broad1:\n',sess.run(mat_broad1))
    print('broad2:\n',sess.run(mat_broad2))

broad1:
 [[4 2]
 [6 4]]
broad2:
 [[6 4]
 [9 8]]


#### Excersise
1) How do you multiply each COLUMN in mat_e by mat_f?

### Reduce

In [71]:
mat_g = tf.constant([[1,2],[1,3]])

red_sum_all = tf.reduce_sum(mat_g)           
red_sum_row = tf.reduce_sum(mat_g, axis = 0)
red_sum_col1 = tf.reduce_sum(mat_g, axis = 1)
red_sum_col2 = tf.reduce_sum(mat_g, axis = 1, keep_dims=True) 

In [72]:
with tf.Session() as sess:
    print('all:\n',sess.run(red_sum_all))
    print('row:\n',sess.run(red_sum_row))
    print('col:\n',sess.run(red_sum_col1))
    print('col:\n',sess.run(red_sum_col2))

all:
 7
row:
 [2 5]
col:
 [3 4]
col:
 [[3]
 [4]]


**Always, always set keep_dims=True!** Also check out tf.reduce_mean, tf.reduce_max, etc.

#### Exercise
1) Say your given a feature matrix as below (20 samples, 10 features each). Normalize the features (i.e. subtract the mean, divide by the std.dev)

In [78]:
features = tf.constant(np.random.uniform(1,10,[20,10]))

2) Implement the [softmax function](https://en.wikipedia.org/wiki/Softmax_function).

### Others
Here are other operations I use often:
- `mat.T`: matrix transpose
- `tf.equal`: compare matrix element-wise
- `tf.argmax`: get the index of max element
- `tf.gather, tf.slice`: often used for indexing, see the [official guide](https://www.tensorflow.org/api_guides/python/array_ops#Slicing_and_Joining) for details
- `tf.while_loop`: when building a computation graph, don't use python for loop, use this
- `tf.zeros, tf.ones`: same as `np.zeros, np.ones`
- `tf.random_normal, tf.random_uniform`

## Tips
- Don't use numpy APIs in between because it will not be part of your computation graph.
- If there's a numpy way to do it, there should be a tf way to do it.
- If you think an operation is too complicated, code it up in numpy first, then convert it to tensorflow. Check if the two outputs match.